version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: diligent_os_postgres
    restart: always
    environment:
      POSTGRES_USER: diligent_user
      POSTGRES_PASSWORD: diligent_password
      POSTGRES_DB: diligent_os_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
